#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libidn
Version  : 1.32
Release  : 10
URL      : http://ftp.gnu.org/gnu/libidn/libidn-1.32.tar.gz
Source0  : http://ftp.gnu.org/gnu/libidn/libidn-1.32.tar.gz
Summary  : IETF stringprep, nameprep, punycode, IDNA text processing.
Group    : Development/Tools
License  : Apache-2.0 GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0 MIT
Requires: libidn-bin
Requires: libidn-lib
Requires: libidn-data
Requires: libidn-doc
Requires: libidn-locales
BuildRequires : docbook-xml
BuildRequires : emacs
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : valgrind

%description
See the end for copying conditions.
Libidn is a package for internationalized string handling based on the
Stringprep, Punycode, IDNA and TLD specifications.  Libidn is a GNU
project.  See the file COPYING for licensing information.

%package bin
Summary: bin components for the libidn package.
Group: Binaries
Requires: libidn-data

%description bin
bin components for the libidn package.


%package data
Summary: data components for the libidn package.
Group: Data

%description data
data components for the libidn package.


%package dev
Summary: dev components for the libidn package.
Group: Development
Requires: libidn-lib
Requires: libidn-bin
Requires: libidn-data

%description dev
dev components for the libidn package.


%package doc
Summary: doc components for the libidn package.
Group: Documentation

%description doc
doc components for the libidn package.


%package lib
Summary: lib components for the libidn package.
Group: Libraries
Requires: libidn-data

%description lib
lib components for the libidn package.


%package locales
Summary: locales components for the libidn package.
Group: Default

%description locales
locales components for the libidn package.


%prep
%setup -q -n libidn-1.32

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang libidn

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/idn

%files data
%defattr(-,root,root,-)
/usr/share/emacs/site-lisp/idna.el
/usr/share/emacs/site-lisp/punycode.el

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f libidn.lang 
%defattr(-,root,root,-)

